import { activeHeroSubtree } from "./spendRules";

/**
 * Generates a SimulationCraft profileset block for the active comparison slots.
 *
 * @param {string[]} buildStrings
 * @param {string[]} buildNames
 * @param {string} classDisplayName
 * @param {string} specDisplayName
 * @param {object} treeData
 * @param {object[]} parsedBuilds
 * @returns {string}
 */
export function generateSimcProfileset(
  buildStrings,
  buildNames,
  classDisplayName,
  specDisplayName,
  treeData,
  parsedBuilds,
) {
  if (!buildStrings || buildStrings.length === 0) return "";

  const lines = [
    "# Generated by Compare Builds (https://acurioustale.de/comparebuilds)",
  ];

  for (let i = 0; i < buildStrings.length; i++) {
    const buildString = buildStrings[i];
    let name = buildNames?.[i]?.trim();

    if (!name) {
      if (specDisplayName && classDisplayName) {
        const parsedBuild = parsedBuilds?.[i];
        const heroSpec =
          parsedBuild && treeData
            ? activeHeroSubtree(treeData.nodes, parsedBuild.nodes)
            : null;
        const prefix = heroSpec ? `${heroSpec} ` : "";
        name = `Build ${i + 1} — ${prefix}${specDisplayName} ${classDisplayName}`;
      } else {
        name = `Build ${i + 1}`;
      }
    }

    // Strip quotes and backslashes to ensure clean SimC profile name
    const cleanName = name.replace(/["\\]/g, "");
    lines.push(`profileset."${cleanName}"+=talent_tree=${buildString}`);
  }

  return lines.join("\n");
}
