import { describe, test, expect } from "vitest";
import { generateSimcProfileset } from "./simcProfile";

describe("generateSimcProfileset", () => {
  test("returns empty string when no builds provided", () => {
    expect(
      generateSimcProfileset([], [], "Death Knight", "Blood", null, []),
    ).toBe("");
  });

  test("uses provided build names and sanitizes quotes/backslashes", () => {
    const builds = ["buildString1", "buildString2"];
    const names = ['My "Awesome" Build\\', "Normal Build"];
    const out = generateSimcProfileset(
      builds,
      names,
      "Death Knight",
      "Blood",
      null,
      [],
    );
    expect(out).toBe(
      `# Generated by Compare Builds (https://comparebuilds.app)\nprofileset."My Awesome Build"+=talents=buildString1\nprofileset."Normal Build"+=talents=buildString2`,
    );
  });

  test("strips control characters (newlines) so a label cannot break the block", () => {
    const builds = ["buildA", "buildB"];
    // A crafted share label can carry a newline (the share API only length-checks
    // labels); it must not split `profileset."NAME"` across physical lines.
    const names = ["Line1\nLine2", "Tab\tName"];
    const out = generateSimcProfileset(builds, names, "Mage", "Fire", null, []);
    expect(out).toBe(
      `# Generated by Compare Builds (https://comparebuilds.app)\nprofileset."Line1Line2"+=talents=buildA\nprofileset."TabName"+=talents=buildB`,
    );
  });

  test("strips non-base64 bytes from the build string so it cannot inject a directive", () => {
    // A crafted share can append bytes past the region the decoder consumes (the
    // string still parses). A trailing newline would split the `talents=` line and
    // inject a top-level SimulationCraft option; the build string must be reduced
    // to its base64 alphabet so it stays one clean token.
    const builds = ["validLoadout\nsim_option=cleave_targets=99"];
    const out = generateSimcProfileset(
      builds,
      ["Evil"],
      "Warrior",
      "Arms",
      null,
      [{}],
    );
    // No physical line may start with an injected directive.
    expect(out.split("\n").some((l) => l.startsWith("sim_option="))).toBe(
      false,
    );
    // Newline and underscores (outside the base64 alphabet) are dropped, so the
    // injected fragment collapses onto the talents value instead of a new line.
    expect(out).toBe(
      `# Generated by Compare Builds (https://comparebuilds.app)\nprofileset."Evil"+=talents=validLoadoutsimoption=cleavetargets=99`,
    );
  });

  test("generates fallback names with hero spec prefix when names are empty", () => {
    const builds = ["buildString1"];
    const names = [""];
    const treeData = {
      nodes: [
        {
          id: 101,
          treeType: "hero",
          name: "Hero Node",
          heroSubtree: "San'layn",
        },
      ],
    };
    const parsedBuilds = [
      {
        nodes: { 101: { pointsInvested: 1 } },
      },
    ];

    const out = generateSimcProfileset(
      builds,
      names,
      "Death Knight",
      "Blood",
      treeData,
      parsedBuilds,
    );

    expect(out).toBe(
      `# Generated by Compare Builds (https://comparebuilds.app)\nprofileset."Build 1 — San'layn Blood Death Knight"+=talents=buildString1`,
    );
  });

  test("generates basic fallback name when spec/class names are absent", () => {
    const builds = ["buildString1"];
    const out = generateSimcProfileset(builds, [], "", "", null, []);
    expect(out).toBe(
      `# Generated by Compare Builds (https://comparebuilds.app)\nprofileset."Build 1"+=talents=buildString1`,
    );
  });

  test("disambiguates duplicate names so no profileset overwrites another", () => {
    const builds = ["buildA", "buildB", "buildC"];
    const names = ["Raid", "Raid", "Raid"];
    const out = generateSimcProfileset(builds, names, "", "", null, []);
    expect(out).toBe(
      `# Generated by Compare Builds (https://comparebuilds.app)\nprofileset."Raid"+=talents=buildA\nprofileset."Raid (2)"+=talents=buildB\nprofileset."Raid (3)"+=talents=buildC`,
    );
  });

  test("disambiguates names that collide only after quote-stripping", () => {
    const builds = ["buildA", "buildB"];
    const names = ["Raid", '"Raid"'];
    const out = generateSimcProfileset(builds, names, "", "", null, []);
    expect(out).toBe(
      `# Generated by Compare Builds (https://comparebuilds.app)\nprofileset."Raid"+=talents=buildA\nprofileset."Raid (2)"+=talents=buildB`,
    );
  });

  test("falls back to the default label when a name is only quotes/backslashes", () => {
    const builds = ["buildA", "buildB"];
    // First name collapses to empty after stripping; it must NOT emit
    // `profileset.""`. Second is a normal name to show the fallback is per-slot.
    const names = ['"\\', "Cleave"];
    const out = generateSimcProfileset(builds, names, "", "", null, []);
    expect(out).toBe(
      `# Generated by Compare Builds (https://comparebuilds.app)\nprofileset."Build 1"+=talents=buildA\nprofileset."Cleave"+=talents=buildB`,
    );
  });

  test("skips slots whose parse failed (explicit null in parsedBuilds)", () => {
    const builds = ["buildA", "corruptBody", "buildC"];
    const names = ["Raid", "Broken", "Mythic"];
    // Middle slot has a valid header (so it was committed) but an unparseable
    // body, so the store recorded null for it.
    const parsedBuilds = [{ nodes: {} }, null, { nodes: {} }];
    const out = generateSimcProfileset(
      builds,
      names,
      "",
      "",
      null,
      parsedBuilds,
    );
    expect(out).toBe(
      `# Generated by Compare Builds (https://comparebuilds.app)\nprofileset."Raid"+=talents=buildA\nprofileset."Mythic"+=talents=buildC`,
    );
  });

  test("emits every slot when parsedBuilds is omitted", () => {
    const builds = ["buildA", "buildB"];
    const names = ["One", "Two"];
    // Undefined entries (no parallel array) are not a failure signal.
    const out = generateSimcProfileset(builds, names, "", "");
    expect(out).toBe(
      `# Generated by Compare Builds (https://comparebuilds.app)\nprofileset."One"+=talents=buildA\nprofileset."Two"+=talents=buildB`,
    );
  });
});
