import { defaultBuildLabel } from "./buildLabel.js";

/**
 * Generates a SimulationCraft profileset block for the active comparison slots.
 *
 * @param {string[]} buildStrings Array of base64 build strings
 * @param {string[]} buildNames Array of custom build names
 * @param {string} classDisplayName Display name of the class
 * @param {string} specDisplayName Display name of the spec
 * @param {object} treeData Spec tree data definition
 * @param {object[]} parsedBuilds Array of parsed build objects
 * @returns {string} SimulationCraft profileset block
 */
export function generateSimcProfileset(
  buildStrings,
  buildNames,
  classDisplayName,
  specDisplayName,
  treeData,
  parsedBuilds,
) {
  if (!buildStrings || buildStrings.length === 0) return "";

  const lines = ["# Generated by Compare Builds (https://comparebuilds.app)"];

  // SimulationCraft keys profilesets by name: a repeated `profileset."NAME"`
  // overwrites the earlier one, silently dropping a build from the sim. Names
  // are not unique upstream (two slots can share a custom name, or a custom
  // name can collide with another slot's fallback, or quote-stripping can
  // collapse two names), so disambiguate any collision with a numeric suffix.
  const usedNames = new Set();

  for (let i = 0; i < buildStrings.length; i++) {
    const buildString = buildStrings[i];

    // Skip slots the app itself couldn't parse. parsedBuilds is kept parallel to
    // buildStrings with an explicit null for a failed (or not-yet-loaded) parse;
    // a committed string can have a valid header but an unparseable body, and
    // emitting its raw `talents=` line would poison the whole profileset in
    // SimulationCraft. A missing/undefined entry (parsedBuilds omitted) is not a
    // failure signal, so only an explicit null is skipped.
    if (parsedBuilds?.[i] === null) continue;

    let name = buildNames?.[i]?.trim();

    if (!name) {
      name = defaultBuildLabel({
        index: i + 1,
        className: classDisplayName,
        specName: specDisplayName,
        treeData,
        parsedBuild: parsedBuilds?.[i],
      });
    }

    // Strip quotes and backslashes to ensure clean simc profile name
    const cleanName = name.replace(/["\\]/g, "");
    // Disambiguate a name already emitted this run so the later build is not
    // silently overwritten by SimulationCraft's name-keyed profilesets.
    let uniqueName = cleanName;
    for (let n = 2; usedNames.has(uniqueName); n++) {
      uniqueName = `${cleanName} (${n})`;
    }
    usedNames.add(uniqueName);
    // SimulationCraft imports the in-game loadout string via `talents=`; there is
    // no `talent_tree=` option, so the wrong keyword would make simc ignore the
    // profileset's talents entirely.
    lines.push(`profileset."${uniqueName}"+=talents=${buildString}`);
  }

  return lines.join("\n");
}
